### ISSUE TITLE
zen-pmu-workaround fails to build on linux 6.16

### ISSUE THREAD

**Issue by symphorien** [rr-debugger/rr#4004]
it used to build on 6.15

error:
```
build flags: SHELL=/nix/store/cfqbabpc7xwg8akbcchqbq3cai6qq2vs-bash-5.2p37/bin/bash -C/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/build M=/build/source/third-party/zen-pmu-workaround modules
make: Entering directory '/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/build'
make[1]: Entering directory '/build/source/third-party/zen-pmu-workaround'
  CC [M]  zen_workaround.o
zen_workaround.c:14:5: warning: no previous prototype for 'set_speclockmap_disable' [-Wmissing-prototypes]
   14 | u64 set_speclockmap_disable(u64 msr) {
      |     ^~~~~~~~~~~~~~~~~~~~~~~
zen_workaround.c:18:5: warning: no previous prototype for 'unset_speclockmap_disable' [-Wmissing-prototypes]
   18 | u64 unset_speclockmap_disable(u64 msr) {
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
zen_workaround.c: In function 'edit_ls_cfg_on_cpu':
zen_workaround.c:29:14: error: implicit declaration of function 'rdmsrl_safe'; did you mean 'rdmsrq_safe'? [-Wimplicit-function-declaration]
   29 |         if (!rdmsrl_safe(MSR_AMD64_LS_CFG, &value)) {
      |              ^~~~~~~~~~~
      |              rdmsrq_safe
zen_workaround.c:32:22: error: implicit declaration of function 'wrmsrl_safe'; did you mean 'wrmsr_safe'? [-Wimplicit-function-declaration]
   32 |                 if (!wrmsrl_safe(MSR_AMD64_LS_CFG, new_value)) {
      |                      ^~~~~~~~~~~
      |                      wrmsr_safe
zen_workaround.c: At top level:
zen_workaround.c:50:6: warning: no previous prototype for 'on_write_msr' [-Wmissing-prototypes]
   50 | void on_write_msr(void *data, unsigned int msr, u64 val, int failed)
      |      ^~~~~~~~~~~~
zen_workaround.c: In function 'on_write_msr':
zen_workaround.c:53:17: error: implicit declaration of function 'native_wrmsrl'; did you mean 'native_wrmsr'? [-Wimplicit-function-declaration]
   53 |                 native_wrmsrl(MSR_AMD64_LS_CFG, set_speclockmap_disable(val));
      |                 ^~~~~~~~~~~~~
      |                 native_wrmsr
make[3]: *** [/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/source/scripts/Makefile.build:287: zen_workaround.o] Error 1
make[2]: *** [/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/source/Makefile:2003: .] Error 2
make[1]: *** [/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/source/Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/build/source/third-party/zen-pmu-workaround'
make: *** [/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/source/Makefile:248: __sub-make] Error 2
make: Leaving directory '/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/build'
```

cc @glandium

**Comment by GitMensch** [comment]
please try https://raw.githubusercontent.com/GitMensch/rr/refs/heads/patch-3/third-party/zen-pmu-workaround/zen_workaround.c and report back; if that works I'll send a PR

**Comment by symphorien** [comment]
still does not build
```
make: Entering directory '/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/build'
make[1]: Entering directory '/build/source/third-party/zen-pmu-workaround'
  CC [M]  zen_workaround.o
zen_workaround.c: In function 'edit_ls_cfg_on_cpu':
zen_workaround.c:30:14: error: implicit declaration of function 'rdmsrl_safe'; did you mean 'rdmsrq_safe'? [-Wimplicit-function-declaration]
   30 |         if (!rdmsrl_safe(MSR_AMD64_LS_CFG, &value)) {
      |              ^~~~~~~~~~~
      |              rdmsrq_safe
zen_workaround.c:33:22: error: implicit declaration of function 'wrmsrl_safe'; did you mean 'wrmsr_safe'? [-Wimplicit-function-declaration]
   33 |                 if (!wrmsrl_safe(MSR_AMD64_LS_CFG, new_value)) {
      |                      ^~~~~~~~~~~
      |                      wrmsr_safe
zen_workaround.c: At top level:
zen_workaround.c:51:6: warning: no previous prototype for 'on_write_msr' [-Wmissing-prototypes]
   51 | void on_write_msr(void *data, unsigned int msr, u64 val, int failed)
      |      ^~~~~~~~~~~~
zen_workaround.c: In function 'on_write_msr':
zen_workaround.c:54:17: error: implicit declaration of function 'native_wrmsrl'; did you mean 'native_wrmsr'? [-Wimplicit-function-declaration]
   54 |                 native_wrmsrl(MSR_AMD64_LS_CFG, set_speclockmap_disable(val));
      |                 ^~~~~~~~~~~~~
      |                 native_wrmsr
make[3]: *** [/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/source/scripts/Makefile.build:287: zen_workaround.o] Error 1
make[2]: *** [/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/source/Makefile:2003: .] Error 2
make[1]: *** [/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/source/Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/build/source/third-party/zen-pmu-workaround'
```

**Comment by GitMensch** [comment]
please use `grep -R rdmsrl_safe /usr` and check if there is a definition somewhere on your system

**Comment by symphorien** [comment]
I find no matches in the installed linux headers. this function was renamed in 6fe22abacd40e259fffec744a02d5ca3febccd68 (x86/msr: Rename 'rdmsrl_safe()' to 'rdmsrq_safe()')

**Comment by symphorien** [comment]
Also affected by  7cbc2ba7c107a1a537524ae505e192f4f88cc209 x86/msr: Rename 'native_wrmsrl()' to 'native_wrmsrq()'

**Comment by symphorien** [comment]
```diff
diff --git a/third-party/zen-pmu-workaround/zen_workaround.c b/third-party/zen-pmu-workaround/zen_workaround.c
index bd014393..510a9cea 100644
--- a/third-party/zen-pmu-workaround/zen_workaround.c
+++ b/third-party/zen-pmu-workaround/zen_workaround.c
@@ -27,10 +27,10 @@ static void edit_ls_cfg_on_cpu(void *info)
 	int cpu = get_cpu();
 	u64 value = 0;
 
-	if (!rdmsrl_safe(MSR_AMD64_LS_CFG, &value)) {
+	if (!rdmsrq_safe(MSR_AMD64_LS_CFG, &value)) {
 		edit_msr_func_t edit_msr = (edit_msr_func_t) info;
 		u64 new_value = edit_msr(value);
-		if (!wrmsrl_safe(MSR_AMD64_LS_CFG, new_value)) {
+		if (!wrmsrq_safe(MSR_AMD64_LS_CFG, new_value)) {
 			pr_info("MSR_AMD64_LS_CFG for cpu %d was 0x%llx, setting to 0x%llx\n",
 			        cpu, value, new_value);
 		} else {
@@ -51,7 +51,7 @@ static void do_zen_workaround(edit_msr_func_t edit_msr)
 void on_write_msr(void *data, unsigned int msr, u64 val, int failed)
 {
 	if (msr == MSR_AMD64_LS_CFG && !(val & SPECLOCKMAP_DISABLE)) {
-		native_wrmsrl(MSR_AMD64_LS_CFG, set_speclockmap_disable(val));
+		native_wrmsrq(MSR_AMD64_LS_CFG, set_speclockmap_disable(val));
 	}
 }
 
```
on top of your patches make it build and work. it still misses ifdefs for older kernel releases.

**Comment by symphorien** [comment]
with this patch:
```diff
diff --git a/third-party/zen-pmu-workaround/zen_workaround.c b/third-party/zen-pmu-workaround/zen_workaround.c
index bd014393..b85e232d 100644
--- a/third-party/zen-pmu-workaround/zen_workaround.c
+++ b/third-party/zen-pmu-workaround/zen_workaround.c
@@ -6,12 +6,20 @@
 #include <linux/module.h>
 #include <linux/tracepoint.h>
 #include <linux/suspend.h>
+#include <linux/version.h>
 #include <asm/msr.h>
 
 #define MODULE_NAME "zen_workaround"
 
 #define SPECLOCKMAP_DISABLE BIT_64(54)
 
+#if LINUX_VERSION_CODE < KERNEL_VERSION(6,16,0)
+#define wrmsrq_safe wrmsrl_safe
+#define rdmsrq_safe rdmsrl_safe
+#define native_wrmsrq native_wrmsrl
+#endif
+
+
 static u64 set_speclockmap_disable(u64 msr) {
 	return msr | SPECLOCKMAP_DISABLE;
 }
@@ -27,10 +35,10 @@ static void edit_ls_cfg_on_cpu(void *info)
 	int cpu = get_cpu();
 	u64 value = 0;
 
-	if (!rdmsrl_safe(MSR_AMD64_LS_CFG, &value)) {
+	if (!rdmsrq_safe(MSR_AMD64_LS_CFG, &value)) {
 		edit_msr_func_t edit_msr = (edit_msr_func_t) info;
 		u64 new_value = edit_msr(value);
-		if (!wrmsrl_safe(MSR_AMD64_LS_CFG, new_value)) {
+		if (!wrmsrq_safe(MSR_AMD64_LS_CFG, new_value)) {
 			pr_info("MSR_AMD64_LS_CFG for cpu %d was 0x%llx, setting to 0x%llx\n",
 			        cpu, value, new_value);
 		} else {
@@ -51,7 +59,7 @@ static void do_zen_workaround(edit_msr_func_t edit_msr)
 void on_write_msr(void *data, unsigned int msr, u64 val, int failed)
 {
 	if (msr == MSR_AMD64_LS_CFG && !(val & SPECLOCKMAP_DISABLE)) {
-		native_wrmsrl(MSR_AMD64_LS_CFG, set_speclockmap_disable(val));
+		native_wrmsrq(MSR_AMD64_LS_CFG, set_speclockmap_disable(val));
 	}
 }
 
```
* the module builds on the following kernel versions; 5_4,6_12,6_15,6_16
* rr stops displaying the error message on 6.16 when the module is loaded.

But please note that I have no idea what I am doing.

**Comment by GitMensch** [comment]
Thank you very much for your "clueless" help (big kudos for checking the git revisions of the rename)!

**Comment by symphorien** [comment]
See https://github.com/rr-debugger/rr/pull/4007
