### PR TITLE
update zen_workaround for kernels > 6.16 and C23

### LINKED ISSUE #4004: zen-pmu-workaround fails to build on linux 6.16
it used to build on 6.15

error:
```
build flags: SHELL=/nix/store/cfqbabpc7xwg8akbcchqbq3cai6qq2vs-bash-5.2p37/bin/bash -C/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/build M=/build/source/third-party/zen-pmu-workaround modules
make: Entering directory '/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/build'
make[1]: Entering directory '/build/source/third-party/zen-pmu-workaround'
  CC [M]  zen_workaround.o
zen_workaround.c:14:5: warning: no previous prototype for 'set_speclockmap_disable' [-Wmissing-prototypes]
   14 | u64 set_speclockmap_disable(u64 msr) {
      |     ^~~~~~~~~~~~~~~~~~~~~~~
zen_workaround.c:18:5: warning: no previous prototype for 'unset_speclockmap_disable' [-Wmissing-prototypes]
   18 | u64 unset_speclockmap_disable(u64 msr) {
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
zen_workaround.c: In function 'edit_ls_cfg_on_cpu':
zen_workaround.c:29:14: error: implicit declaration of function 'rdmsrl_safe'; did you mean 'rdmsrq_safe'? [-Wimplicit-function-declaration]
   29 |         if (!rdmsrl_safe(MSR_AMD64_LS_CFG, &value)) {
      |              ^~~~~~~~~~~
      |              rdmsrq_safe
zen_workaround.c:32:22: error: implicit declaration of function 'wrmsrl_safe'; did you mean 'wrmsr_safe'? [-Wimplicit-function-declaration]
   32 |                 if (!wrmsrl_safe(MSR_AMD64_LS_CFG, new_value)) {
      |                      ^~~~~~~~~~~
      |                      wrmsr_safe
zen_workaround.c: At top level:
zen_workaround.c:50:6: warning: no previous prototype for 'on_write_msr' [-Wmissing-prototypes]
   50 | void on_write_msr(void *data, unsigned int msr, u64 val, int failed)
      |      ^~~~~~~~~~~~
zen_workaround.c: In function 'on_write_msr':
zen_workaround.c:53:17: error: implicit declaration of function 'native_wrmsrl'; did you mean 'native_wrmsr'? [-Wimplicit-function-declaration]
   53 |                 native_wrmsrl(MSR_AMD64_LS_CFG, set_speclockmap_disable(val));
      |                 ^~~~~~~~~~~~~
      |                 native_wrmsr
make[3]: *** [/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/source/scripts/Makefile.build:287: zen_workaround.o] Error 1
make[2]: *** [/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/source/Makefile:2003: .] Error 2
make[1]: *** [/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/source/Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/build/source/third-party/zen-pmu-workaround'
make: *** [/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/source/Makefile:248: __sub-make] Error 2
make: Leaving directory '/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/build'
```

cc @glandium

### PR DESCRIPTION
**Pull request by GitMensch**
kernel functions renamed in 7cbc2ba7c107a1a537524ae505e192f4f88cc209  and 6fe22abacd40e259fffec744a02d5ca3febccd68 which both arrived with 6.16. rc1

fixes #4004

co-authored by @symphorien

### CODE REVIEW

**Comment by symphorien** [comment]
it does not build 
```
make: Leaving directory '/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/build'
error: builder for '/nix/store/whb5j2vqai8zxk714k1ws86d17afd402-rr-zen_workaround-5.9.0.drv' failed with exit code 2;
       last 25 log lines:
       >   CC [M]  zen_workaround.o
       > zen_workaround.c: In function 'edit_ls_cfg_on_cpu':
       > zen_workaround.c:38:14: error: implicit declaration of function 'rdmsrl_safe'; did you mean 'rdmsrq_safe'? [-Wimplicit-function-declaration]
       >    38 |         if (!rdmsrl_safe(MSR_AMD64_LS_CFG, &value)) {
       >       |              ^~~~~~~~~~~
       >       |              rdmsrq_safe
       > zen_workaround.c:41:22: error: implicit declaration of function 'wrmsrl_safe'; did you mean 'wrmsr_safe'? [-Wimplicit-function-declaration]
       >    41 |                 if (!wrmsrl_safe(MSR_AMD64_LS_CFG, new_value)) {
       >       |                      ^~~~~~~~~~~
       >       |                      wrmsr_safe
       > zen_workaround.c: At top level:
       > zen_workaround.c:59:6: warning: no previous prototype for 'on_write_msr' [-Wmissing-prototypes]
       >    59 | void on_write_msr(void *data, unsigned int msr, u64 val, int failed)
       >       |      ^~~~~~~~~~~~
       > zen_workaround.c: In function 'on_write_msr':
       > zen_workaround.c:62:17: error: implicit declaration of function 'native_wrmsrl'; did you mean 'native_wrmsr'? [-Wimplicit-function-declaration]
       >    62 |                 native_wrmsrl(MSR_AMD64_LS_CFG, set_speclockmap_disable(val));
       >       |                 ^~~~~~~~~~~~~
       >       |                 native_wrmsr
       > make[3]: *** [/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/source/scripts/Makefile.build:287: zen_workaround.o] Error 1
       > make[2]: *** [/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/source/Makefile:2003: .] Error 2
       > make[1]: *** [/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/source/Makefile:248: __sub-make] Error 2
       > make[1]: Leaving directory '/build/source/third-party/zen-pmu-workaround'
       > make: *** [/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/source/Makefile:248: __sub-make] Error 2
       > make: Leaving directory '/nix/store/2l0bd52ch90r0r1msj0banw4smii8igk-linux-6.16-dev/lib/modules/6.16.0/build'
       For full logs, run:
         nix-store -l /nix/store/whb5j2vqai8zxk714k1ws86d17afd402-rr-zen_workaround-5.9.0.drv
```
I think you forgot to replace the `l`s by `q`s in the function names.

**Comment by GitMensch** [comment]
can you please note what the error in the patch is?

**Comment by dzaima** [comment]
You added `#define wrmsrq_safe 	wrmsrl_safe` & co, but don't ever use the `wrmsrq_safe` you define, as the code still has `wrmsrl_safe`.

**Comment by symphorien** [comment]
To gain time I opened another PR https://github.com/rr-debugger/rr/pull/4007

**Comment by GitMensch** [comment]
Thanks,. I've rebased and force-pushed
