### ISSUE TITLE
rr build error with clang 18.1.3: Monkeypatcher.cc:531:22: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]

### ISSUE THREAD

**Issue by dholbert** [rr-debugger/rr#3805]
Similar to #3802 - this is now the next build error I get when I build on a system with clang 18.1.3:
```
/scratch/work/tools/rr/rr/src/Monkeypatcher.cc:531:22: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
  531 |   uint8_t jump_patch[patch_region_size];
      |                      ^~~~~~~~~~~~~~~~~
/scratch/work/tools/rr/rr/src/Monkeypatcher.cc:531:22: note: read of non-const variable 'patch_region_size' is not allowed in a constant expression
/scratch/work/tools/rr/rr/src/Monkeypatcher.cc:530:10: note: declared here
  530 |   size_t patch_region_size = instruction_length + hook.patch_region_length;
      |          ^
/scratch/work/tools/rr/rr/src/Monkeypatcher.cc:531:22: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
  531 |   uint8_t jump_patch[patch_region_size];
      |                      ^~~~~~~~~~~~~~~~~
/scratch/work/tools/rr/rr/src/Monkeypatcher.cc:609:10: note: in instantiation of function template specialization 'rr::patch_syscall_with_hook_x86ish<rr::X86SysenterVsyscallSyscallHook, rr::X86SyscallStubExtendedJump, rr::X86TrapInstructionStubExtendedJump>' requested here
  609 |   return patch_syscall_with_hook_x86ish<X86SysenterVsyscallSyscallHook,
      |          ^
/scratch/work/tools/rr/rr/src/Monkeypatcher.cc:531:22: note: read of non-const variable 'patch_region_size' is not allowed in a constant expression
  531 |   uint8_t jump_patch[patch_region_size];
      |                      ^
/scratch/work/tools/rr/rr/src/Monkeypatcher.cc:530:10: note: declared here
  530 |   size_t patch_region_size = instruction_length + hook.patch_region_length;
      |          ^
/scratch/work/tools/rr/rr/src/Monkeypatcher.cc:531:22: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
  531 |   uint8_t jump_patch[patch_region_size];
      |                      ^~~~~~~~~~~~~~~~~
/scratch/work/tools/rr/rr/src/Monkeypatcher.cc:625:10: note: in instantiation of function template specialization 'rr::patch_syscall_with_hook_x86ish<rr::X64JumpMonkeypatch, rr::X64SyscallStubExtendedJump, rr::X64TrapInstructionStubExtendedJump>' requested here
  625 |   return patch_syscall_with_hook_x86ish<X64JumpMonkeypatch,
      |          ^
/scratch/work/tools/rr/rr/src/Monkeypatcher.cc:531:22: note: read of non-const variable 'patch_region_size' is not allowed in a constant expression
  531 |   uint8_t jump_patch[patch_region_size];
      |                      ^
/scratch/work/tools/rr/rr/src/Monkeypatcher.cc:530:10: note: declared here
  530 |   size_t patch_region_size = instruction_length + hook.patch_region_length;
      |          ^

```

**Comment by dholbert** [comment]
I think that's just 3 errors all pointing to the same line, actually (though it appeared as quoted above in my build output). Here's the just the first copy to be a bit more readable:
```
rr/src/Monkeypatcher.cc:531:22: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
  531 |   uint8_t jump_patch[patch_region_size];
      |                      ^~~~~~~~~~~~~~~~~
```

**Comment by dholbert** [comment]
Fortunately this isn't too whack-a-mole-ish after the previous copy of this warning -- I think this is the only remaining instance of this warning.

At least: when I do a (successful) full release-mode build (`cmake -DCMAKE_BUILD_TYPE=Release ../rr` which turns off warnings-as-errors) , this is the only build warning that I get.

**Comment by dholbert** [comment]
Thanks @rocallahan !  I confirmed that I can build successfully with that fix. \o/
