### ISSUE TITLE
Fails to build on ubuntu 18.04 due to call_gettid.c

### ISSUE THREAD

**Issue by jfkthame** [rr-debugger/rr#2833]
The call_gettid.c file that was added in 35d477f3b371b7f0b99a44540056e6b1c73eaaaa causes rr to fail to build for me on Ubuntu 18.04:

> error: implicit declaration of function ‘gettid’; did you mean ‘getgid’?

Just adding a declaration doesn't fix things, because it then fails to link ("undefined reference to function ‘gettid’").

`man gettid` tells me there is no glibc wrapper for it.

**Comment by rocallahan** [comment]
I swear this got fixed but maybe I just dreamed that.

**Comment by rocallahan** [comment]
Fixed in ef2ddde82258f32e779a59db8c0039d2af5ead9e

**Comment by khuey** [comment]
I think we fixed this issue somewhere else and then I added another instance of it.

**Comment by jfkthame** [comment]
Thanks for the prompt attention!
