### ISSUE TITLE
blake2b.c.o: plugin needed to handle lto object

### ISSUE THREAD

**Issue by dm-tesla** [rr-debugger/rr#3268]
Unable to build on Ubuntu 20.04:
```
[ 94%] Built target constructor
/usr/bin/ld.bfd: CMakeFiles/rr.dir/third-party/blake2/sse/blake2b.c.o: plugin needed to handle lto object
/usr/bin/ld.bfd: /tmp/lto-llvm-636802.o: in function `rr::process_files_thread(void*)':
/home/kvark/Code/rr/src/PackCommand.cc:127: undefined reference to `blake2b_init'
/usr/bin/ld.bfd: /home/kvark/Code/rr/src/PackCommand.cc:141: undefined reference to `blake2b_update'
/usr/bin/ld.bfd: /home/kvark/Code/rr/src/PackCommand.cc:146: undefined reference to `blake2b_final'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by rocallahan** [comment]
Sorry about the delay. What options did you use to build?

**Comment by dm-tesla** [comment]
Huh, weird. Tried again on 1f5f6d611d8de5e619422b2490280b924f01c6eb with this config `cmake .. -Ddisable32bit=ON` and it built fine.

**Comment by denizzzka** [comment]
Same problem on the current ~master with `-Ddisable32bit=ON`

I found what build is possible only for `-DCMAKE_BUILD_TYPE=Debug` target in this case, owtherwise it still complains `plugin needed to handle lto object`
